# Generated by Django 4.2.11 on 2025-04-09 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_network_clipboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipboard',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
