# Generated by Django 4.2.11 on 2025-04-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_clipboard', '0002_rename_password_hash_clipboard_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
