# Generated by Django 4.2.11 on 2025-04-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_clipboard', '0003_alter_clipboard_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='version',
            field=models.PositiveIntegerField(default=0, verbose_name='版本号'),
        ),
    ]
