# Generated by Django 4.2.11 on 2025-06-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_clipboard', '0004_clipboard_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
