# Generated by Django 4.2.11 on 2024-09-19 07:36

import app_video.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(blank=True, max_length=128, verbose_name='视频名称')),
                ('video_size', models.IntegerField(blank=True, verbose_name='文件大小(bytes)')),
                ('video_time', models.IntegerField(blank=True, null=True, verbose_name='视频时间长度')),
                ('video_type', models.CharField(blank=True, max_length=64, verbose_name='视频类型')),
                ('video_path', models.FileField(upload_to=app_video.models.create_file_path, verbose_name='文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
