# Generated by Django 4.2.11 on 2024-09-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_time',
            new_name='video_duration',
        ),
    ]
