# Generated by Django 4.2.11 on 2024-09-24 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0002_rename_video_time_video_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
