# Generated by Django 4.2.11 on 2024-10-17 08:24

import app_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0003_video_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_bitrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频码率'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频高度'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频宽度'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to=app_video.models.create_file_path, verbose_name='视频路径'),
        ),
    ]
