version: "3.4"
services:
  nginx:
    image: nginx:1.24.0-bullseye
    container_name: domo_nginx
    restart: always
    # 挂载目录
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./domo_front:/usr/local/share/domo_front
      - ./domo_backend/static:/usr/local/share/static
    ports:
      # 设置端口
      - "80:80"
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      domo_net:
        ipv4_address: 172.16.238.2

  domo:
    image: domo_app:1.4.0
    container_name: domo_app
    restart: always
    # 挂载目录
    volumes:
      - ./domo_backend/static:/usr/local/domo/static
      - ./domo_backend/db:/usr/local/domo/db
      - ./domo_backend/logs:/usr/local/domo/logs
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      domo_net:
        ipv4_address: 172.16.238.3

networks:
  domo_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
