# Generated by Django 4.2.11 on 2024-10-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_size', models.IntegerField(blank=True, verbose_name='图片大小(bytes)')),
                ('image_path', models.CharField(blank=True, max_length=100, verbose_name='图片路径')),
                ('image_width', models.IntegerField(blank=True, verbose_name='图片宽度')),
                ('image_height', models.IntegerField(blank=True, verbose_name='图片高度')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'db_table': 'wallpaper',
            },
        ),
    ]
