# Generated by Django 4.2.11 on 2024-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='image_name',
            field=models.CharField(default='2024-10-22 16:23:57.188773.jpg', max_length=64, verbose_name='图片名'),
            preserve_default=False,
        ),
    ]
