# Generated by Django 4.2.11 on 2024-10-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallpaper', '0002_wallpaper_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='保存图片哈希值'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='source_image_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='原始图片哈希值'),
        ),
    ]
