# Generated by Django 4.2.11 on 2024-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to=128, verbose_name='文章路径'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True, verbose_name='文件大小(bytes)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.IntegerField(blank=True, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=128, verbose_name='文件名'),
        ),
    ]
