# Generated by Django 4.2.11 on 2024-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0002_alter_file_file_path_alter_file_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=128, verbose_name='文件路径'),
        ),
    ]
