# Generated by Django 4.2.11 on 2024-06-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0003_remove_file_file_path_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file_path',
        ),
    ]
