# Generated by Django 4.2.11 on 2024-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_file', '0004_rename_file_file_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='文件类型'),
        ),
    ]
