# Generated by Django 4.2.11 on 2024-06-13 04:01

import app_file.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_file', '0005_alter_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(null=True, upload_to=app_file.models.create_file_path, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
    ]
