# Generated by Django 4.2.11 on 2024-08-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_file', '0008_alter_file_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=128, verbose_name='用户 IP')),
                ('download_time', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_file.file', verbose_name='文件')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'file_download_log',
            },
        ),
    ]
