# Generated by Django 4.2.11 on 2024-08-26 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_file', '0009_filedownloadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedownloadlog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_file.file', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='filedownloadlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
