# Generated by Django 4.2.11 on 2024-04-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=64, verbose_name='文章名称')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('abstract', models.CharField(max_length=512, verbose_name='内容摘要')),
                ('article_status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过'), (3, '隐藏'), (4, '删除')], default=0, verbose_name='文章状态')),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_article.article', verbose_name='文章')),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
        ),
    ]
