# Generated by Django 4.2.11 on 2024-05-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_article_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
        migrations.RemoveField(
            model_name='articlemodifyrecord',
            name='modify_user',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.SmallIntegerField(choices=[(0, '显示'), (1, '隐藏')], default=0, verbose_name='文章状态'),
        ),
    ]
