# Generated by Django 4.2.11 on 2024-05-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0003_remove_article_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=256, verbose_name='内容摘要'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
