# Generated by Django 4.2.11 on 2024-05-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0004_alter_article_abstract_alter_article_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_name',
            new_name='title',
        ),
    ]
