# Generated by Django 4.2.11 on 2024-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0005_rename_article_content_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_path',
            field=models.CharField(blank=True, max_length=128, verbose_name='文章路径'),
        ),
    ]
