# Generated by Django 4.2.11 on 2024-05-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0006_article_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, verbose_name='文章标题'),
        ),
    ]
