# Generated by Django 4.2.11 on 2024-08-16 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_article', '0008_article_author_alter_article_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlemodifyrecord',
            table='article_modify_record',
        ),
        migrations.CreateModel(
            name='ArticleActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=128, verbose_name='用户 IP')),
                ('action_type', models.SmallIntegerField(choices=[(0, '浏览'), (1, '点赞')], default=0, verbose_name='动作类型')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_article.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'article_activity_log',
            },
        ),
    ]
