# Generated by Django 4.2.11 on 2024-08-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0009_alter_articlemodifyrecord_table_articleactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_article.article', verbose_name='文章')),
            ],
            options={
                'db_table': 'article_edit_log',
            },
        ),
        migrations.DeleteModel(
            name='ArticleModifyRecord',
        ),
    ]
