# Generated by Django 4.2.11 on 2024-09-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0012_articleeditlog_edit_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
